events {
    worker_connections 1024;
}

http {
    split_clients "${msec}" $random_backend {
        50%     pinjampro-kelompok5.up.railway.app;
        *       pinjampro-server2.up.railway.app;
    }

    map $http_accept $is_html {
        "~*text/html" 1;
        default       0;
    }

    map $http_cache_control $is_refresh {
        "~*no-cache"  1;
        "~*max-age=0" 1;
        default       0;
    }

    map $cookie_srv $cookie_domain {
        "railway 1" pinjampro-kelompok5.up.railway.app;
        "railway 2" pinjampro-server2.up.railway.app;
        default   "";
    }

    map $my_target $set_cookie_srv {
        pinjampro-kelompok5.up.railway.app "railway 1";
        pinjampro-server2.up.railway.app "railway 2";
    }

    server {
        listen 80;
        server_name localhost;

        resolver 8.8.8.8 1.1.1.1 valid=300s;
        resolver_timeout 5s;

        location / {
            set $my_target $cookie_domain;

            if ($my_target = "") {
                set $my_target $random_backend;
            }

            set $force_switch "${is_html}${is_refresh}";
            if ($force_switch = "11") {
                set $my_target $random_backend;
            }

            proxy_pass https://$my_target$request_uri;

            proxy_ssl_server_name on;
            proxy_set_header Host $my_target;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            add_header Set-Cookie "srv=$set_cookie_srv; Path=/; Max-Age=3600" always;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            add_header X-Served-By $my_target always;
        }
    }
}
