events {}

http {
    # Choose backend based on client IP hash
    split_clients "${http_x_forwarded_for}" $target_domain {
        50% https://pinjampro-kelompok5.up.railway.app;
        *   https://pinjampro-server2.up.railway.app;
    }

    server {
        # The port will be replaced at container start by the Docker CMD (uses $PORT env var)
        listen 80;  # placeholder
        location / {
            proxy_pass $target_domain;
            proxy_ssl_server_name on;
            # Forward the original Host header of the request to the upstream service
            proxy_set_header Host $proxy_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # Prevent Nginx from rewriting redirects back to the load balancer
            proxy_redirect off;
        }
    }
}
